apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
<<<<<<< HEAD
  namespace: monitoring
=======
  labels:
    app: prometheus
>>>>>>> fb74ba9e5ea1a37f37db3961a1b8c7e4d5e2f671
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
<<<<<<< HEAD

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'flask-app'
        metrics_path: /metrics
        static_configs:
          - targets: ['34.42.228.136:5000']
=======
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "flipkart-recommender"
        metrics_path: /metrics
        static_configs:
          - targets: ["flipkart-recommender-service:5000"]
>>>>>>> fb74ba9e5ea1a37f37db3961a1b8c7e4d5e2f671
